tunnel: ponix
credentials-file: /etc/cloudflared/credentials.json
protocol: http2
ha-connections: 2  # Only try for 2 connections instead of 4
loglevel: info     # Reduce log verbosity

ingress:
  - hostname: "api.ponix.dev"
    service: http://ponix-all-in-one:3001
    originRequest:
      httpHostHeader: "api.ponix.dev"
  - service: http_status:404

metrics: 0.0.0.0:8080