name: ponix
services:
  ponix-all-in-one:
    image: ponix-all-in-one:latest
    ports:
      - 3001:3001
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-lgtm:4318
      PORT: "3001"
      DATABASE_PASSWORD: ponix
      DATABASE_USERNAME: ponix
      DATABASE_URL: db:5432
      DATABASE: ponix
      TTN_APPLICATION: ponix-cloud
      TTN_SERVER_NAME: ponix
      TTN_REGION: nam1
    env_file:
      - .env
    depends_on:
      - otel-lgtm
      - db
    networks:
      - ponix
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    networks:
      - ponix
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks:
      - ponix
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - ponix
    depends_on:
      - nats
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - ponix
    depends_on:
      - nats
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ponix
      POSTGRES_USER: ponix
      POSTGRES_DB: ponix
    networks:
      - ponix
  # influxdb:
  #   image: influxdb:2.7-alpine
  #   ports:
  #     - 8086:8086
  #   environment:
  #     DOCKER_INFLUXDB_INIT_MODE: setup
  #     DOCKER_INFLUXDB_INIT_USERNAME: admin
  #     DOCKER_INFLUXDB_INIT_PASSWORD: admin123456
  #     DOCKER_INFLUXDB_INIT_ORG: ponix
  #     DOCKER_INFLUXDB_INIT_BUCKET: webhooks
  #     DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ponix-super-secret-auth-token
  #   volumes:
  #     - influxdb-data:/var/lib/influxdb2
  #     - influxdb-config:/etc/influxdb2
  #   networks:
  #     - ponix
  # telegraf:
  #   image: telegraf:1.31-alpine
  #   volumes:
  #     - ./.influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #   environment:
  #     INFLUX_TOKEN: ponix-super-secret-auth-token
  #     INFLUX_ORG: ponix
  #     INFLUX_BUCKET: webhooks
  #     INFLUX_URL: http://influxdb:8086
  #   depends_on:
  #     - influxdb
  #     - nats
  #   networks:
  #     - ponix
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yaml run
    volumes:
      - ./.cloudflared/cloudflared-config.yaml:/etc/cloudflared/config.yaml:ro
      - ${HOME}/.cloudflared/ponix-api.json:/etc/cloudflared/credentials.json:ro
      - ${HOME}/.cloudflared/cert.pem:/etc/cloudflared/cert.pem:ro 
    depends_on:
      - ponix-all-in-one
    networks:
      - ponix
    restart: unless-stopped

networks:
  ponix:
    name: ponix
volumes:
  influxdb-data:
  influxdb-config:
