name: ponix
services:
  ponix-all-in-one:
    image: ponix-all-in-one:latest
    ports:
      - 3001:3001
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-lgtm:4318
      PORT: "3001"
      DATABASE_PASSWORD: ponix
      DATABASE_USERNAME: ponix
      DATABASE_URL: db:5432
      DATABASE: ponix
      TTN_APPLICATION: ponix-cloud
      TTN_SERVER_NAME: ponix
      TTN_REGION: nam1
    env_file:
      - .env
    depends_on:
      - otel-lgtm
      - db
    networks:
      - ponix
  otel-lgtm:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    networks:
      - ponix
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks:
      - ponix
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - ponix
    depends_on:
      - nats
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - ponix
    depends_on:
      - nats
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ponix
      POSTGRES_USER: ponix
      POSTGRES_DB: ponix
    networks:
      - ponix
networks:
  ponix:
    name: ponix
