[package]
name = "ponix-gateway"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.29", features = ["full"] }
rand = { version = "0.8" }
telemetry = { workspace = true }
