// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EndDevice struct {
	ID             string
	Name           string
	Description    pgtype.Text
	OrganizationID string
	Status         int32
	DataType       int32
	HardwareType   int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type LorawanConfig struct {
	ID               string
	EndDeviceID      string
	DeviceEui        string
	ApplicationEui   string
	ApplicationID    string
	ApplicationKey   string
	NetworkKey       pgtype.Text
	ActivationMethod int32
	FrequencyPlanID  string
	HardwareTypeID   string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type LorawanFrequencyPlan struct {
	ID          string
	Name        string
	Description pgtype.Text
	Region      string
	CreatedAt   pgtype.Timestamptz
}

type LorawanHardwareType struct {
	ID              string
	Name            string
	Description     pgtype.Text
	Manufacturer    string
	Model           string
	FirmwareVersion pgtype.Text
	HardwareVersion pgtype.Text
	Profile         pgtype.Text
	LorawanVersion  int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type Organization struct {
	ID        string
	Name      string
	Status    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID             string
	OrganizationID string
	FirstName      string
	LastName       string
	Status         int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
