// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: network_server.sql

package sqlc

import (
	"context"
)

const createNetworkServer = `-- name: CreateNetworkServer :one
INSERT INTO
    network_servers (id, system_id, name, status, iot_platform)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, system_id, name, status, iot_platform
`

type CreateNetworkServerParams struct {
	ID          string
	SystemID    string
	Name        string
	Status      int32
	IotPlatform int32
}

func (q *Queries) CreateNetworkServer(ctx context.Context, arg CreateNetworkServerParams) (NetworkServer, error) {
	row := q.db.QueryRow(ctx, createNetworkServer,
		arg.ID,
		arg.SystemID,
		arg.Name,
		arg.Status,
		arg.IotPlatform,
	)
	var i NetworkServer
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.Name,
		&i.Status,
		&i.IotPlatform,
	)
	return i, err
}
