// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: organization.sql

package sqlc

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO
    organizations (id, name, status)
VALUES
    ($1, $2, $3)
RETURNING
    id, name, status
`

type CreateOrganizationParams struct {
	ID     string
	Name   string
	Status int32
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name, arg.Status)
	var i Organization
	err := row.Scan(&i.ID, &i.Name, &i.Status)
	return i, err
}
